import { initNav } from './modules/nav';
import { initTabs } from './modules/tabs';
import { initAdmin } from './modules/admin';
import { initReveal } from './modules/reveal';
import { initSliders } from './modules/slider';
import { initTheme } from './modules/theme';
import { initImageLoading } from './modules/image-loading';
import { initLanguageSwitcher } from './modules/language-switcher';
import { initChatbot } from './modules/chatbot';
import { initCountUp } from './modules/count-up';
import { initScrollProgress } from './modules/scroll-progress';
import { initFluidSmoke } from './modules/fluid-smoke';
import { initThermalHeatmap } from './modules/thermal-heatmap';
import { initVisibility } from './modules/visibility';
import { initBackToTop } from './modules/back-to-top';
import { initCookieBanner } from './modules/cookie-banner';
import { initSearchModal } from './modules/search-modal';

initNav();
initTabs();
initAdmin();
initReveal();
initSliders();
initTheme();
initImageLoading();
initLanguageSwitcher();
initChatbot();
initCountUp();
initScrollProgress();
initFluidSmoke();
initThermalHeatmap();
initVisibility();
initBackToTop();
initCookieBanner();
initSearchModal();
